name: Contribution snake

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake grid
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lendradxx
          svg_out_path: assets/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: assets
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}